### ISSUE TITLE
Possibility to send multiple mails to a group

### ISSUE THREAD

**Issue by wernerkrauss** [tractorcow/silverstripe-comments-notifications#10]
E.g. if we want to send mails to all users of a specific group (chef editors)

**Comment by tractorcow** [comment]
You can add an extension to your page, implement updateNotificationRecipients(), and then loop through all users in the group you wish to send to, adding each member to the $list property. (Just add the `Member` object to that array).

Sorry this should be documented properly. :)

**Comment by tractorcow** [comment]
Also, you should be using https://github.com/silverstripe-labs/comment-notifications, since this fork is going to be deprecated.
