### ISSUE TITLE
Notification email is sent but has no content.

### ISSUE THREAD

**Issue by micahsheets** [tractorcow/silverstripe-comments-notifications#7]
I have installed the plugin in the correct folder name. _config/config.yml is left at defaults. I have dev/build?flush=all so the ss file should be available. However the email still comes through blank. Any ideas of what might be going on? I have tried to Debug::show different data but when i do that I get an error that the CommentNotificationsEmail.ss file cannot be found in theme ''. I think that I may not be able to debug this way as the Debug Controller is now in play and is not aware of the theme name. I have tried copying the ss file into my theme/templates folder but that does not fix the issue.

**Comment by tractorcow** [comment]
This module is abandoned: Please go to https://github.com/silverstripe-labs/comment-notifications
