### ISSUE TITLE
Support multiple recipients

### ISSUE THREAD

**Issue by clyonsEIS** [tractorcow/silverstripe-comments-notifications#8]
Hi Damian, thanks for the useful module.
I'm going to need a way to support multiple recipients with this; I notice the first limitation is by use of a single Email field.

Are there plans to add this? I'd be happy to contribute; do you have thoughts on how you'd like it implemented?

**Comment by tractorcow** [comment]
Please use the https://github.com/silverstripe-labs/comment-notifications module, which supports multiple recipients.
